# Generated by Django 4.2.23 on 2025-11-27 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('name', models.CharField(help_text='Tên nhà hàng', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug', unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('phone_number', models.CharField(help_text='Số điện thoại', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('address', models.TextField(help_text='Địa chỉ')),
                ('city', models.CharField(help_text='Thành phố', max_length=100)),
                ('district', models.CharField(help_text='Quận/Huyện', max_length=100)),
                ('ward', models.CharField(blank=True, help_text='Phường/Xã', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Mã bưu điện', max_length=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Vĩ độ', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Kinh độ', max_digits=9)),
                ('logo', models.ImageField(blank=True, help_text='Logo', null=True, upload_to='restaurants/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh bìa', null=True, upload_to='restaurants/covers/')),
                ('opening_time', models.TimeField(help_text='Giờ mở cửa')),
                ('closing_time', models.TimeField(help_text='Giờ đóng cửa')),
                ('is_open', models.BooleanField(default=True, help_text='Đang mở cửa')),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Đánh giá trung bình', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0, help_text='Tổng số đánh giá')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, help_text='Đơn hàng tối thiểu', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí giao hàng', max_digits=10)),
                ('delivery_radius', models.DecimalField(decimal_places=2, default=5, help_text='Bán kính giao hàng (km)', max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Nhà hàng',
                'verbose_name_plural': 'Nhà hàng',
                'db_table': 'restaurants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('table_number', models.CharField(help_text='Số bàn', max_length=50)),
                ('capacity', models.IntegerField(help_text='Sức chứa (số người)', validators=[django.core.validators.MinValueValidator(1)])),
                ('floor', models.IntegerField(default=1, help_text='Tầng')),
                ('section', models.CharField(blank=True, help_text='Khu vực', max_length=100, null=True)),
                ('status', models.CharField(choices=[('available', 'Trống'), ('reserved', 'Đã đặt'), ('occupied', 'Đang sử dụng'), ('maintenance', 'Bảo trì')], default='available', help_text='Trạng thái', max_length=20)),
                ('x_position', models.DecimalField(blank=True, decimal_places=2, help_text='Vị trí X', max_digits=10, null=True)),
                ('y_position', models.DecimalField(blank=True, decimal_places=2, help_text='Vị trí Y', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
                ('restaurant', models.ForeignKey(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Bàn',
                'verbose_name_plural': 'Bàn',
                'db_table': 'tables',
                'ordering': ['restaurant', 'floor', 'table_number'],
            },
        ),
    ]
