# Generated by Django 4.2.23 on 2025-11-28 13:35

import config.storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ảnh bìa', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='restaurants/covers/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='restaurants/logos/'),
        ),
    ]
