# Generated by Django 4.2.23 on 2025-12-10 07:41

import config.storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0004_alter_restaurant_latitude_alter_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='Tên chi nhánh/nhà hàng', max_length=200),
        ),
        migrations.CreateModel(
            name='RestaurantChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('name', models.CharField(help_text='Tên chuỗi nhà hàng', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug', unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('logo', models.ImageField(blank=True, help_text='Logo chuỗi', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='chains/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Ảnh bìa chuỗi', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='chains/covers/')),
                ('contact_email', models.EmailField(blank=True, help_text='Email liên hệ', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, help_text='Hotline', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text='Website', null=True)),
                ('default_minimum_order', models.DecimalField(decimal_places=2, default=0, help_text='Đơn hàng tối thiểu mặc định', max_digits=10)),
                ('default_delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí giao hàng mặc định', max_digits=10)),
                ('default_delivery_radius', models.DecimalField(decimal_places=2, default=5, help_text='Bán kính giao hàng mặc định (km)', max_digits=8)),
                ('enable_auto_assignment', models.BooleanField(default=True, help_text='Tự động phân đơn hàng cho chi nhánh gần nhất')),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
                ('owner', models.ForeignKey(blank=True, help_text='Chủ chuỗi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chuỗi nhà hàng',
                'verbose_name_plural': 'Chuỗi nhà hàng',
                'db_table': 'restaurant_chains',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='chain',
            field=models.ForeignKey(blank=True, help_text='Chuỗi nhà hàng (để trống nếu là nhà hàng độc lập)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='restaurants.restaurantchain'),
        ),
    ]
