# Generated by Django 4.2.23 on 2025-12-18 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_name_restaurantchain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('base_fee', models.DecimalField(decimal_places=2, default=15000, help_text='Phí giao hàng cơ bản (đ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('per_km_fee', models.DecimalField(decimal_places=2, default=5000, help_text='Phí mỗi km (đ/km)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('free_distance_km', models.DecimalField(decimal_places=2, default=0, help_text='Số km miễn phí (km)', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí giao hàng tối thiểu (đ)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Phí giao hàng tối đa (đ) - để trống nếu không giới hạn', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('enable_surge_pricing', models.BooleanField(default=False, help_text='Bật tính năng tăng giá giờ cao điểm')),
                ('surge_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Hệ số nhân giá giờ cao điểm (1.0 - 3.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.0)])),
                ('surge_start_time', models.TimeField(blank=True, help_text='Giờ bắt đầu cao điểm (VD: 11:00)', null=True)),
                ('surge_end_time', models.TimeField(blank=True, help_text='Giờ kết thúc cao điểm (VD: 13:00)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang sử dụng config này')),
                ('restaurant', models.OneToOneField(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_pricing_config', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Cấu hình giá vận chuyển',
                'verbose_name_plural': 'Cấu hình giá vận chuyển',
                'db_table': 'delivery_pricing_configs',
            },
        ),
    ]
