# Generated by Django 4.2.23 on 2025-11-27 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('order_number', models.CharField(help_text='Mã đơn hàng', max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('dine_in', 'Ăn tại chỗ'), ('takeaway', 'Mang đi'), ('delivery', 'Giao hàng')], default='dine_in', help_text='Loại đơn hàng', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('delivering', 'Đang giao hàng'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('refunded', 'Đã hoàn tiền')], default='pending', help_text='Trạng thái', max_length=20)),
                ('delivery_address', models.TextField(blank=True, help_text='Địa chỉ giao hàng', null=True)),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Vĩ độ địa chỉ giao hàng', max_digits=9, null=True)),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Kinh độ địa chỉ giao hàng', max_digits=9, null=True)),
                ('delivery_phone', models.CharField(blank=True, help_text='Số điện thoại giao hàng', max_length=20, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền món ăn', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax', models.DecimalField(decimal_places=2, default=0, help_text='Thuế', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí giao hàng', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, help_text='Giảm giá', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Tổng cộng', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('customer_notes', models.TextField(blank=True, help_text='Ghi chú từ khách hàng', null=True)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Thời gian dự kiến (phút)', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Thời gian hoàn thành', null=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('item_name', models.CharField(help_text='Tên món', max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, help_text='Giá tại thời điểm đặt', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity', models.IntegerField(default=1, help_text='Số lượng', validators=[django.core.validators.MinValueValidator(1)])),
                ('special_instructions', models.TextField(blank=True, help_text='Yêu cầu đặc biệt', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Tổng tiền', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('menu_item', models.ForeignKey(help_text='Món ăn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dishes.menuitem')),
                ('order', models.ForeignKey(help_text='Đơn hàng', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
                'db_table': 'order_items',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
