# Generated by Django 4.2.23 on 2025-12-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_name_restaurantchain_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assignment_distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Khoảng cách đến chi nhánh (km)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assignment_method',
            field=models.CharField(choices=[('manual', 'Thủ công'), ('auto', 'Tự động'), ('customer', 'Khách chọn')], default='manual', help_text='Phương thức phân chi nhánh', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='chain',
            field=models.ForeignKey(blank=True, help_text='Chuỗi nhà hàng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurantchain'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Chi nhánh xử lý đơn hàng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurants.restaurant'),
        ),
    ]
