# Generated by Django 4.2.23 on 2025-12-19 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentmethod_icon'),
        ('orders', '0003_order_assignment_distance_order_assignment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, help_text='Phương thức thanh toán', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payments.paymentmethod'),
        ),
    ]
