# Generated by Django 4.2.23 on 2025-11-27 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('reservation_number', models.CharField(help_text='Mã đặt bàn', max_length=50, unique=True)),
                ('reservation_date', models.DateField(help_text='Ngày đặt')),
                ('reservation_time', models.TimeField(help_text='Giờ đặt')),
                ('number_of_guests', models.IntegerField(help_text='Số lượng khách', validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('checked_in', 'Đã check-in'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='pending', help_text='Trạng thái', max_length=20)),
                ('contact_name', models.CharField(help_text='Tên người đặt', max_length=200)),
                ('contact_phone', models.CharField(help_text='Số điện thoại', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Email', max_length=254, null=True)),
                ('special_requests', models.TextField(blank=True, help_text='Yêu cầu đặc biệt', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú nội bộ', null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, help_text='Thời gian check-in', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Thời gian hoàn thành', null=True)),
            ],
            options={
                'verbose_name': 'Đặt bàn',
                'verbose_name_plural': 'Đặt bàn',
                'db_table': 'reservations',
                'ordering': ['reservation_date', 'reservation_time'],
            },
        ),
    ]
