# Generated by Django 4.2.23 on 2025-12-30 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='assigned_staff',
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Số tiền cọc đã thanh toán', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_required',
            field=models.DecimalField(decimal_places=2, default=300000, help_text='Số tiền cọc bắt buộc', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('app', 'Mobile App'), ('phone', 'Điện thoại'), ('walk_in', 'Walk-in')], default='website', help_text='Nguồn đặt bàn', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Sinh nhật'), ('anniversary', 'Kỷ niệm'), ('business', 'Công việc'), ('date', 'Hẹn hò'), ('other', 'Khác')], help_text='Dịp đặc biệt', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', help_text='Trạng thái', max_length=20),
        ),
    ]
