# Generated by Django 4.2.23 on 2025-12-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_remove_reservation_assigned_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='source',
        ),
    ]
