# Generated by Django 4.2.23 on 2025-11-27 07:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('name', models.CharField(help_text='Tên danh mục', max_length=100)),
                ('slug', models.SlugField(help_text='URL slug')),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh', null=True, upload_to='categories/')),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'categories',
                'ordering': ['restaurant', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('name', models.CharField(help_text='Tên món', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug')),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá gốc (nếu có khuyến mãi)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, help_text='Hình ảnh', null=True, upload_to='menu_items/')),
                ('calories', models.IntegerField(blank=True, help_text='Calories', null=True)),
                ('preparation_time', models.IntegerField(blank=True, help_text='Thời gian chuẩn bị (phút)', null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, help_text='Đánh giá trung bình', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.IntegerField(default=0, help_text='Tổng số đánh giá')),
                ('is_available', models.BooleanField(default=True, help_text='Còn hàng')),
                ('is_featured', models.BooleanField(default=False, help_text='Nổi bật')),
                ('is_vegetarian', models.BooleanField(default=False, help_text='Món chay')),
                ('is_spicy', models.BooleanField(default=False, help_text='Cay')),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('category', models.ForeignKey(blank=True, help_text='Danh mục', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='dishes.category')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Món ăn',
                'db_table': 'menu_items',
                'ordering': ['restaurant', 'category', 'display_order', 'name'],
            },
        ),
    ]
