# Generated by Django 4.2.23 on 2025-11-28 13:35

import config.storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='menu_items/'),
        ),
    ]
