# Generated by Django 4.2.23 on 2025-12-10 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_name_restaurantchain_and_more'),
        ('dishes', '0003_alter_category_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'display_order', 'name'], 'verbose_name': 'Món ăn', 'verbose_name_plural': 'Món ăn'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='category',
            name='chain',
            field=models.ForeignKey(blank=True, help_text='Chuỗi nhà hàng (menu chung cho cả chuỗi)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurantchain'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='chain',
            field=models.ForeignKey(blank=True, help_text='Chuỗi nhà hàng (menu chung cho cả chuỗi)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurantchain'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Nhà hàng độc lập (để trống nếu thuộc chuỗi)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='restaurants.restaurant'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Nhà hàng độc lập (để trống nếu thuộc chuỗi)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['chain', 'slug'], name='categories_chain_i_064354_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['restaurant', 'slug'], name='categories_restaur_0e9f80_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['chain', 'slug'], name='menu_items_chain_i_45f7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'slug'], name='menu_items_restaur_4f1126_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['chain', 'is_available'], name='menu_items_chain_i_f383fa_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['restaurant', 'is_available'], name='menu_items_restaur_d2ad1f_idx'),
        ),
    ]
