# Generated by Django 4.2.23 on 2025-12-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_alter_category_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='last_rated_at',
            field=models.DateTimeField(blank=True, help_text='Last time this item was rated', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rating_distribution',
            field=models.JSONField(blank=True, default=dict, help_text="Distribution of ratings: {'1_star': count, '2_star': count, ...}"),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='verified_purchase_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of ratings from verified purchases', max_digits=5),
        ),
    ]
