# Generated by Django 4.2.23 on 2025-12-25 15:33

import config.storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_menuitem_last_rated_at_menuitem_rating_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('image', models.ImageField(help_text='Hình ảnh bổ sung', storage=config.storage.storage.MinIOMediaStorage(), upload_to='menu_items/')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text cho hình ảnh (cho accessibility)', max_length=200, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('menu_item', models.ForeignKey(help_text='Món ăn', on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='dishes.menuitem')),
            ],
            options={
                'verbose_name': 'Hình ảnh món ăn',
                'verbose_name_plural': 'Hình ảnh món ăn',
                'db_table': 'menu_item_images',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['menu_item', 'display_order'], name='menu_item_i_menu_it_c83a8a_idx')],
            },
        ),
    ]
