# Generated by Django 4.2.23 on 2025-12-17 04:17

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0005_alter_restaurant_name_restaurantchain_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0005_menuitem_last_rated_at_menuitem_rating_distribution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tổng tạm tính')),
                ('tax', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Thuế')),
                ('total_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tổng phí vận chuyển')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Giảm giá')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Tổng cộng')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Giỏ hàng',
                'verbose_name_plural': 'Giỏ hàng',
                'db_table': 'carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200, verbose_name='Tên món')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá món')),
                ('item_image', models.CharField(blank=True, max_length=255, verbose_name='Hình ảnh món')),
                ('restaurant_name', models.CharField(max_length=200, verbose_name='Tên nhà hàng')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng')),
                ('special_instructions', models.TextField(blank=True, verbose_name='Yêu cầu đặc biệt')),
                ('delivery_address', models.TextField(blank=True, verbose_name='Địa chỉ giao hàng')),
                ('delivery_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Vĩ độ giao hàng')),
                ('delivery_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Kinh độ giao hàng')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Phí vận chuyển')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Thành tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Giỏ hàng')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurantchain', verbose_name='Chuỗi nhà hàng')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.menuitem', verbose_name='Món ăn')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant', verbose_name='Nhà hàng')),
            ],
            options={
                'verbose_name': 'Món trong giỏ hàng',
                'verbose_name_plural': 'Các món trong giỏ hàng',
                'db_table': 'cart_items',
                'indexes': [models.Index(fields=['cart', 'created_at'], name='cart_items_cart_id_24922a_idx'), models.Index(fields=['restaurant'], name='cart_items_restaur_f857ed_idx'), models.Index(fields=['menu_item'], name='cart_items_menu_it_0f4a8d_idx'), models.Index(fields=['cart', 'restaurant'], name='cart_items_cart_id_16cfce_idx')],
                'unique_together': {('cart', 'menu_item')},
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user'], name='carts_user_id_b1c689_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['created_at'], name='carts_created_22c862_idx'),
        ),
    ]
