# Generated by Django 4.2.23 on 2025-12-17 07:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_delivery_fee',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_latitude',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='delivery_longitude',
        ),
        migrations.AlterField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tổng giá trị các món trong giỏ (chưa bao gồm phí ship, thuế, discount)', max_digits=10, verbose_name='Tổng giá trị món ăn'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='VD: Ít cay, không hành, v.v.', verbose_name='Yêu cầu đặc biệt cho món ăn'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giá món x Số lượng', max_digits=10, verbose_name='Thành tiền'),
        ),
    ]
