# Generated by Django 4.2.23 on 2025-11-27 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('payment_number', models.CharField(help_text='Mã thanh toán', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('processing', 'Đang xử lý'), ('completed', 'Đã thanh toán'), ('failed', 'Thất bại'), ('refunded', 'Đã hoàn tiền'), ('cancelled', 'Đã hủy')], default='pending', help_text='Trạng thái', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='VND', help_text='Đơn vị tiền tệ', max_length=3)),
                ('transaction_id', models.CharField(blank=True, help_text='Mã giao dịch', max_length=200, null=True, unique=True)),
                ('payment_gateway', models.CharField(blank=True, help_text='Cổng thanh toán', max_length=100, null=True)),
                ('gateway_response', models.JSONField(blank=True, help_text='Phản hồi từ gateway', null=True)),
                ('card_last_four', models.CharField(blank=True, help_text='4 số cuối thẻ', max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, help_text='Loại thẻ', max_length=50, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Thời gian thanh toán', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='Thời gian hoàn tiền', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Lý do thất bại', null=True)),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('name', models.CharField(help_text='Tên phương thức', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Mã phương thức', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('icon', models.ImageField(blank=True, help_text='Icon', null=True, upload_to='payment_methods/')),
                ('is_active', models.BooleanField(default=True, help_text='Đang hoạt động')),
                ('requires_online', models.BooleanField(default=False, help_text='Yêu cầu thanh toán online')),
                ('display_order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Phương thức thanh toán',
                'verbose_name_plural': 'Phương thức thanh toán',
                'db_table': 'payment_methods',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
