# Generated by Django 4.2.23 on 2025-11-28 13:35

import config.storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='icon',
            field=models.ImageField(blank=True, help_text='Icon', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='payment_methods/'),
        ),
    ]
