# Generated by Django 4.2.23 on 2025-12-22 02:10

from django.db import migrations


def create_vnpay_payment_method(apps, schema_editor):
    """
    Create VNPay payment method
    """
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')

    # Create VNPay payment method
    PaymentMethod.objects.create(
        name='VNPay',
        code='vnpay',
        description='Thanh toán qua cổng VNPay',
        is_active=True,
        requires_online=True,
        display_order=10,
    )


def reverse_create_vnpay_payment_method(apps, schema_editor):
    """
    Reverse the creation of VNPay payment method
    """
    PaymentMethod = apps.get_model('payments', 'PaymentMethod')
    PaymentMethod.objects.filter(code='vnpay').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentmethod_icon'),
    ]

    operations = [
        migrations.RunPython(
            create_vnpay_payment_method,
            reverse_create_vnpay_payment_method,
        ),
    ]
