# Generated by Django 4.2.23 on 2025-12-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_payment_method'),
        ('reservations', '0003_remove_reservation_assigned_staff_and_more'),
        ('payments', '0004_add_vnpay_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.OneToOneField(blank=True, help_text='Đặt bàn (payment là cọc cho reservation)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, help_text='Đơn hàng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order'),
        ),
    ]
