# Generated by Django 4.2.23 on 2025-11-27 07:32

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('user_type', models.CharField(choices=[('customer', 'Khách hàng'), ('staff', 'Nhân viên'), ('manager', 'Quản lý'), ('admin', 'Quản trị viên')], default='customer', help_text='Loại người dùng', max_length=20)),
                ('phone_number', models.CharField(blank=True, help_text='Số điện thoại', max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Số điện thoại phải có định dạng: '+999999999'. Tối đa 15 số.", regex='^\\+?1?\\d{9,15}$')])),
                ('avatar', models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Ngày sinh', null=True)),
                ('address', models.TextField(blank=True, help_text='Địa chỉ', null=True)),
                ('city', models.CharField(blank=True, help_text='Thành phố', max_length=100, null=True)),
                ('district', models.CharField(blank=True, help_text='Quận/Huyện', max_length=100, null=True)),
                ('ward', models.CharField(blank=True, help_text='Phường/Xã', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Mã bưu điện', max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Vĩ độ', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Kinh độ', max_digits=9, null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Đã xác thực')),
                ('is_active', models.BooleanField(default=True, help_text='Tài khoản đang hoạt động')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('employee_id', models.CharField(help_text='Mã nhân viên', max_length=50, unique=True)),
                ('position', models.CharField(help_text='Chức vụ', max_length=100)),
                ('hire_date', models.DateField(help_text='Ngày vào làm')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, help_text='Lương', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang làm việc')),
                ('restaurant', models.ForeignKey(blank=True, help_text='Nhà hàng làm việc', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='restaurants.restaurant')),
                ('user', models.OneToOneField(help_text='Người dùng', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ nhân viên',
                'verbose_name_plural': 'Hồ sơ nhân viên',
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('preferred_language', models.CharField(choices=[('vi', 'Tiếng Việt'), ('en', 'English')], default='vi', help_text='Ngôn ngữ ưa thích', max_length=10)),
                ('loyalty_points', models.IntegerField(default=0, help_text='Điểm tích lũy')),
                ('total_orders', models.IntegerField(default=0, help_text='Tổng số đơn hàng')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Tổng chi tiêu', max_digits=12)),
                ('receive_promotions', models.BooleanField(default=True, help_text='Nhận khuyến mãi')),
                ('receive_notifications', models.BooleanField(default=True, help_text='Nhận thông báo')),
                ('user', models.OneToOneField(help_text='Người dùng', on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hồ sơ khách hàng',
                'verbose_name_plural': 'Hồ sơ khách hàng',
                'db_table': 'customer_profiles',
            },
        ),
    ]
