# Generated by Django 4.2.23 on 2025-11-28 13:35

import config.storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Ảnh đại diện', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='avatars/'),
        ),
    ]
