# Generated by Django 4.2.23 on 2025-12-02 15:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_alter_restaurant_cover_image_alter_restaurant_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('name', models.CharField(help_text='Tên quy tắc thưởng', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Mô tả', null=True)),
                ('bonus_type', models.CharField(choices=[('sales_target', 'Đạt doanh số'), ('shift_count', 'Số ca làm'), ('customer_rating', 'Đánh giá khách hàng'), ('attendance', 'Tỷ lệ đi làm'), ('custom', 'Tùy chỉnh')], help_text='Loại thưởng', max_length=20)),
                ('condition_value', models.DecimalField(decimal_places=2, help_text='Giá trị điều kiện (doanh số, số ca, rating, tỷ lệ %)', max_digits=12)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Số tiền cố định'), ('percentage', 'Phần trăm lương')], default='fixed', help_text='Cách tính thưởng', max_length=20)),
                ('bonus_amount', models.DecimalField(decimal_places=2, help_text='Số tiền thưởng (nếu calculation_type = fixed) hoặc % (nếu = percentage)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_date', models.DateField(help_text='Ngày bắt đầu áp dụng')),
                ('expiry_date', models.DateField(blank=True, help_text='Ngày hết hạn', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang áp dụng')),
                ('restaurant', models.ForeignKey(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Quy tắc thưởng',
                'verbose_name_plural': 'Quy tắc thưởng',
                'db_table': 'bonus_rules',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('employee_id', models.CharField(help_text='Mã nhân viên', max_length=50)),
                ('position', models.CharField(help_text='Chức vụ (Ví dụ: Phục vụ, Đầu bếp, Quản lý)', max_length=100)),
                ('department', models.CharField(blank=True, help_text='Bộ phận (Ví dụ: Phục vụ, Bếp, Bar)', max_length=100, null=True)),
                ('hire_date', models.DateField(help_text='Ngày vào làm')),
                ('status', models.CharField(choices=[('active', 'Đang làm việc'), ('on_leave', 'Nghỉ phép'), ('suspended', 'Tạm ngưng'), ('terminated', 'Đã nghỉ việc')], default='active', help_text='Trạng thái', max_length=20)),
                ('termination_date', models.DateField(blank=True, help_text='Ngày nghỉ việc', null=True)),
                ('restaurant', models.ForeignKey(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='restaurants.restaurant')),
                ('user', models.ForeignKey(help_text='Người dùng', on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Nhân viên',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('month', models.IntegerField(help_text='Tháng', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('year', models.IntegerField(help_text='Năm', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('period_start', models.DateField(help_text='Ngày bắt đầu kỳ lương')),
                ('period_end', models.DateField(help_text='Ngày kết thúc kỳ lương')),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tổng giờ làm', max_digits=8)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giờ làm thường', max_digits=8)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Giờ làm thêm', max_digits=8)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lương cơ bản', max_digits=12)),
                ('overtime_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lương làm thêm', max_digits=12)),
                ('total_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tổng thưởng', max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tổng khấu trừ', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Lương thực nhận', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('calculated', 'Đã tính'), ('approved', 'Đã duyệt'), ('paid', 'Đã trả')], default='draft', help_text='Trạng thái', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, help_text='Thời gian tính lương', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Thời gian duyệt', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='Thời gian trả lương', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người duyệt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Nhân viên', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='salary_and_bonus.employee')),
                ('restaurant', models.ForeignKey(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương',
                'db_table': 'payrolls',
                'ordering': ['-year', '-month', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('date', models.DateField(help_text='Ngày làm việc')),
                ('scheduled_start_time', models.TimeField(help_text='Giờ bắt đầu dự kiến')),
                ('scheduled_end_time', models.TimeField(help_text='Giờ kết thúc dự kiến')),
                ('actual_start_time', models.DateTimeField(blank=True, help_text='Thời gian check-in thực tế', null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, help_text='Thời gian check-out thực tế', null=True)),
                ('break_duration_minutes', models.IntegerField(default=0, help_text='Thời gian nghỉ (phút)', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('checked_in', 'Đã check-in'), ('checked_out', 'Đã check-out'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='scheduled', help_text='Trạng thái', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('location', models.CharField(blank=True, help_text='Địa điểm làm việc', max_length=200, null=True)),
                ('employee', models.ForeignKey(help_text='Nhân viên', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='salary_and_bonus.employee')),
                ('restaurant', models.ForeignKey(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Ca làm việc',
                'verbose_name_plural': 'Ca làm việc',
                'db_table': 'shifts',
                'ordering': ['-date', '-scheduled_start_time'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('position', models.CharField(help_text='Chức vụ (Ví dụ: Phục vụ, Đầu bếp)', max_length=100)),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Lương theo giờ (VND)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.5'), help_text='Hệ số lương làm thêm (Ví dụ: 1.5 = 150% lương thường)', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('effective_date', models.DateField(help_text='Ngày bắt đầu áp dụng')),
                ('expiry_date', models.DateField(blank=True, help_text='Ngày hết hạn (null = không hết hạn)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Đang áp dụng')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('restaurant', models.ForeignKey(help_text='Nhà hàng (null = áp dụng cho tất cả)', on_delete=django.db.models.deletion.CASCADE, related_name='salary_rates', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Mức lương',
                'verbose_name_plural': 'Mức lương',
                'db_table': 'salary_rates',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('item_type', models.CharField(choices=[('base_salary', 'Lương cơ bản'), ('overtime', 'Lương làm thêm'), ('bonus', 'Thưởng'), ('deduction', 'Khấu trừ'), ('allowance', 'Phụ cấp')], help_text='Loại khoản', max_length=20)),
                ('description', models.CharField(help_text='Mô tả', max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Số lượng (giờ, số ca, v.v.)', max_digits=10)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Đơn giá (lương/giờ, số tiền thưởng, v.v.)', max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Thành tiền', max_digits=12)),
                ('bonus_rule', models.ForeignKey(blank=True, help_text='Quy tắc thưởng (nếu áp dụng)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='salary_and_bonus.bonusrule')),
                ('payroll', models.ForeignKey(help_text='Bảng lương', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salary_and_bonus.payroll')),
                ('shift', models.ForeignKey(blank=True, help_text='Ca làm việc (nếu áp dụng)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_items', to='salary_and_bonus.shift')),
            ],
            options={
                'verbose_name': 'Chi tiết lương',
                'verbose_name_plural': 'Chi tiết lương',
                'db_table': 'payroll_items',
                'ordering': ['payroll', 'item_type', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee', 'date'], name='shifts_employe_c0aa31_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['restaurant', 'date'], name='shifts_restaur_84d2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['status', 'date'], name='shifts_status_1abef9_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrate',
            index=models.Index(fields=['restaurant', 'position', 'is_active'], name='salary_rate_restaur_7417ef_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryrate',
            index=models.Index(fields=['effective_date', 'expiry_date'], name='salary_rate_effecti_bea7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollitem',
            index=models.Index(fields=['payroll', 'item_type'], name='payroll_ite_payroll_bd5e7f_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'year', 'month'], name='payrolls_employe_ba049b_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['restaurant', 'year', 'month'], name='payrolls_restaur_cc7fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payrolls_status_366245_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['restaurant', 'status'], name='employees_restaur_a779ac_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['user', 'restaurant'], name='employees_user_id_4e299a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('restaurant', 'employee_id')},
        ),
        migrations.AddIndex(
            model_name='bonusrule',
            index=models.Index(fields=['restaurant', 'is_active'], name='bonus_rules_restaur_c7e40e_idx'),
        ),
        migrations.AddIndex(
            model_name='bonusrule',
            index=models.Index(fields=['bonus_type', 'is_active'], name='bonus_rules_bonus_t_51852c_idx'),
        ),
    ]
