# Generated by Django 4.2.23 on 2025-12-16 16:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0005_menuitem_last_rated_at_menuitem_rating_distribution_and_more'),
        ('orders', '0003_order_assignment_distance_order_assignment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemRating',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, help_text='Detailed review of the menu item', null=True)),
                ('review_images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('helpful_count', models.IntegerField(default=0)),
                ('not_helpful_count', models.IntegerField(default=0)),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='User actually ordered this item')),
                ('is_approved', models.BooleanField(default=True, help_text='Review passed moderation')),
                ('moderation_notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='dishes.menuitem')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to='orders.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'menu_item_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Rating Categories',
                'db_table': 'rating_categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RatingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ratings.menuitemrating')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_responses',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['rating', 'is_public'], name='rating_resp_rating__5c333f_idx'), models.Index(fields=['responder', 'created_at'], name='rating_resp_respond_9d11a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='RatingHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_helpful', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.menuitemrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_helpful',
                'indexes': [models.Index(fields=['rating', 'is_helpful'], name='rating_help_rating__839bbd_idx'), models.Index(fields=['user', 'created_at'], name='rating_help_user_id_ba8a39_idx')],
                'unique_together': {('rating', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='menuitemrating',
            index=models.Index(fields=['menu_item', 'rating'], name='menu_item_r_menu_it_a43fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemrating',
            index=models.Index(fields=['user', 'created_at'], name='menu_item_r_user_id_af133a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemrating',
            index=models.Index(fields=['created_at'], name='menu_item_r_created_aab01d_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemrating',
            index=models.Index(fields=['is_approved'], name='menu_item_r_is_appr_763584_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemrating',
            index=models.Index(fields=['is_verified_purchase'], name='menu_item_r_is_veri_f369ce_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemrating',
            index=models.Index(fields=['rating', 'is_approved'], name='menu_item_r_rating_5fb8b2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemrating',
            unique_together={('menu_item', 'user')},
        ),
    ]
