# Generated by Django 4.2.23 on 2025-12-26 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_menuitemimage'),
        ('orders', '0004_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(help_text='Review content/text')),
                ('is_verified_purchase', models.BooleanField(default=False, help_text='User actually ordered this item')),
                ('is_approved', models.BooleanField(default=True, help_text='Review passed moderation')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of reviewer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Review created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Review last updated date')),
                ('menu_item', models.ForeignKey(help_text='Menu item being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dishes.menuitem')),
                ('order_item', models.ForeignKey(blank=True, help_text='Linked order item for verified purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.orderitem')),
                ('user', models.ForeignKey(help_text='User who wrote the review', on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menu Item Review',
                'verbose_name_plural': 'Menu Item Reviews',
                'db_table': 'menu_item_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Response content')),
                ('is_public', models.BooleanField(default=True, help_text='Show response publicly')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Response created date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Response last updated date')),
                ('responder', models.ForeignKey(help_text='Restaurant staff/owner who responded', on_delete=django.db.models.deletion.CASCADE, related_name='review_responses', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(help_text='Review being responded to', on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='ratings.menuitemreview')),
            ],
            options={
                'verbose_name': 'Review Response',
                'verbose_name_plural': 'Review Responses',
                'db_table': 'review_responses',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='menuitemrating',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='menuitemrating',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='menuitemrating',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='menuitemrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='RatingCategory',
        ),
        migrations.AlterUniqueTogether(
            name='ratinghelpful',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ratinghelpful',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='ratinghelpful',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ratingresponse',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='ratingresponse',
            name='responder',
        ),
        migrations.DeleteModel(
            name='MenuItemRating',
        ),
        migrations.DeleteModel(
            name='RatingHelpful',
        ),
        migrations.DeleteModel(
            name='RatingResponse',
        ),
        migrations.AddIndex(
            model_name='reviewresponse',
            index=models.Index(fields=['review', 'is_public'], name='review_resp_review__f8ce28_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewresponse',
            index=models.Index(fields=['responder', 'created_at'], name='review_resp_respond_907269_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['menu_item', 'rating'], name='menu_item_r_menu_it_01414f_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['user', 'created_at'], name='menu_item_r_user_id_3e8506_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['created_at'], name='menu_item_r_created_51676c_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['is_approved'], name='menu_item_r_is_appr_d3a78a_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['is_verified_purchase'], name='menu_item_r_is_veri_f53906_idx'),
        ),
        migrations.AddIndex(
            model_name='menuitemreview',
            index=models.Index(fields=['rating', 'is_approved'], name='menu_item_r_rating_eb2155_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemreview',
            unique_together={('menu_item', 'user')},
        ),
    ]
