# Generated by Django 4.2.23 on 2025-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('metric_type', models.CharField(choices=[('daily_revenue', 'Doanh thu theo ngày'), ('monthly_revenue', 'Doanh thu theo tháng'), ('total_orders', 'Tổng số đơn hàng'), ('total_customers', 'Tổng số khách hàng'), ('average_order_value', 'Giá trị đơn hàng trung bình'), ('popular_items', 'Món ăn phổ biến'), ('reservation_stats', 'Thống kê đặt bàn'), ('customer_retention', 'Tỷ lệ khách hàng quay lại')], help_text='Loại metric', max_length=50)),
                ('date', models.DateField(help_text='Ngày')),
                ('value', models.DecimalField(decimal_places=2, help_text='Giá trị', max_digits=15)),
                ('metadata', models.JSONField(blank=True, help_text='Dữ liệu bổ sung', null=True)),
            ],
            options={
                'verbose_name': 'Chỉ số dashboard',
                'verbose_name_plural': 'Chỉ số dashboard',
                'db_table': 'dashboard_metrics',
                'ordering': ['-date', 'restaurant'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('order_number', models.CharField(help_text='Mã đơn hàng', max_length=50)),
                ('restaurant_name', models.CharField(help_text='Tên nhà hàng', max_length=200)),
                ('order_date', models.DateTimeField(help_text='Ngày đặt hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Tổng tiền', max_digits=10)),
                ('status', models.CharField(help_text='Trạng thái', max_length=20)),
                ('items_summary', models.JSONField(help_text='Tóm tắt món ăn')),
            ],
            options={
                'verbose_name': 'Lịch sử mua hàng',
                'verbose_name_plural': 'Lịch sử mua hàng',
                'db_table': 'order_history',
                'ordering': ['-order_date'],
            },
        ),
    ]
