# Generated by Django 4.2.23 on 2025-11-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        ('orders', '0001_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='customer',
            field=models.ForeignKey(help_text='Khách hàng', on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(help_text='Đơn hàng', on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='orders.order'),
        ),
        migrations.AddField(
            model_name='dashboardmetric',
            name='restaurant',
            field=models.ForeignKey(help_text='Nhà hàng', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_metrics', to='restaurants.restaurant'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['customer', '-order_date'], name='order_histo_custome_aa37c9_idx'),
        ),
        migrations.AddIndex(
            model_name='orderhistory',
            index=models.Index(fields=['order_number'], name='order_histo_order_n_ccaca5_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['restaurant', 'metric_type', '-date'], name='dashboard_m_restaur_ff3acf_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['date'], name='dashboard_m_date_8b5000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardmetric',
            unique_together={('restaurant', 'metric_type', 'date')},
        ),
    ]
