# Generated by Django 4.2.23 on 2025-11-30 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Email để xác thực', max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Số điện thoại để xác thực', max_length=17, null=True)),
                ('code', models.CharField(help_text='Mã xác thực 6 số', max_length=6)),
                ('verification_type', models.CharField(choices=[('email', 'Email Verification'), ('phone', 'Phone Verification'), ('password_reset', 'Password Reset')], help_text='Loại xác thực', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Số lần thử sai')),
                ('max_attempts', models.IntegerField(default=3, help_text='Số lần thử tối đa')),
                ('is_verified', models.BooleanField(default=False, help_text='Đã xác thực')),
                ('is_used', models.BooleanField(default=False, help_text='Đã sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Thời gian hết hạn')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mã xác thực',
                'verbose_name_plural': 'Mã xác thực',
                'db_table': 'verification_codes',
                'indexes': [models.Index(fields=['email', 'verification_type'], name='verificatio_email_771583_idx'), models.Index(fields=['phone_number', 'verification_type'], name='verificatio_phone_n_5b1b1e_idx'), models.Index(fields=['code', 'expires_at'], name='verificatio_code_51c15f_idx'), models.Index(fields=['is_verified', 'is_used'], name='verificatio_is_veri_a8641a_idx')],
                'unique_together': {('phone_number', 'verification_type', 'is_used'), ('email', 'verification_type', 'is_used')},
            },
        ),
        migrations.CreateModel(
            name='RefreshTokenSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_token', models.TextField(help_text='Mã hóa refresh token')),
                ('device_info', models.JSONField(default=dict, help_text='Thông tin device/browser')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Thời gian hết hạn refresh token')),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('logout', 'User Logout'), ('expired', 'Token Expired'), ('security', 'Security Revoke'), ('new_device', 'New Device Login')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refresh Token Session',
                'verbose_name_plural': 'Refresh Token Sessions',
                'db_table': 'refresh_token_sessions',
                'indexes': [models.Index(fields=['user', 'is_active'], name='refresh_tok_user_id_bd75cc_idx'), models.Index(fields=['refresh_token'], name='refresh_tok_refresh_bbc182_idx'), models.Index(fields=['expires_at'], name='refresh_tok_expires_7302ed_idx'), models.Index(fields=['ip_address', 'created_at'], name='refresh_tok_ip_addr_2d3b5e_idx')],
            },
        ),
    ]
