# Generated by Django 4.2.23 on 2025-12-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='verificationcode',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='verificationcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('email', 'verification_type'), name='unique_active_email_verification'),
        ),
        migrations.AddConstraint(
            model_name='verificationcode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('phone_number', 'verification_type'), name='unique_active_phone_verification'),
        ),
    ]
