# Generated by Django 4.2.23 on 2025-11-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('room_number', models.CharField(help_text='Mã phòng chat', max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('customer_support', 'Hỗ trợ khách hàng'), ('order_support', 'Hỗ trợ đơn hàng'), ('reservation_support', 'Hỗ trợ đặt bàn'), ('general', 'Tổng đài')], default='general', help_text='Loại phòng', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('waiting', 'Chờ phản hồi'), ('closed', 'Đã đóng')], default='active', help_text='Trạng thái', max_length=20)),
                ('subject', models.CharField(blank=True, help_text='Chủ đề', max_length=200, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, help_text='Tin nhắn cuối', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Thời gian đóng', null=True)),
            ],
            options={
                'verbose_name': 'Phòng chat',
                'verbose_name_plural': 'Phòng chat',
                'db_table': 'chat_rooms',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('message_type', models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'File'), ('system', 'Hệ thống')], default='text', help_text='Loại tin nhắn', max_length=20)),
                ('content', models.TextField(help_text='Nội dung')),
                ('attachment', models.FileField(blank=True, help_text='File đính kèm', null=True, upload_to='chat_attachments/')),
                ('is_read', models.BooleanField(default=False, help_text='Đã đọc')),
                ('read_at', models.DateTimeField(blank=True, help_text='Thời gian đọc', null=True)),
                ('room', models.ForeignKey(help_text='Phòng chat', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
