# Generated by Django 4.2.23 on 2025-11-27 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
        ('orders', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='Người gửi', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='customer',
            field=models.ForeignKey(help_text='Khách hàng', on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Đơn hàng liên quan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='orders.order'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='reservation',
            field=models.ForeignKey(blank=True, help_text='Đặt bàn liên quan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Nhân viên phụ trách', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='messages_room_id_72ec70_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'is_read'], name='messages_sender__bb2957_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_number'], name='chat_rooms_room_nu_c5fe93_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['customer', 'status'], name='chat_rooms_custome_66d692_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['staff', 'status'], name='chat_rooms_staff_i_532f0c_idx'),
        ),
    ]
