# Generated by Django 4.2.23 on 2025-11-28 13:35

import config.storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='File đính kèm', null=True, storage=config.storage.storage.MinIOMediaStorage(), upload_to='chat_attachments/'),
        ),
    ]
