# Generated by Django 4.2.23 on 2026-01-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_add_chatbot_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Độ tin cậy của phân loại ý định', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='entities',
            field=models.JSONField(blank=True, default=dict, help_text='Các thực thể được trích xuất', null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='intent',
            field=models.CharField(blank=True, help_text='Ý định của tin nhắn', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_bot_response',
            field=models.BooleanField(default=False, help_text='Đây là phản hồi từ chatbot'),
        ),
    ]
