# Generated by Django 4.2.23 on 2026-01-05 09:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dishes', '0006_menuitemimage'),
        ('restaurants', '0006_deliverypricingconfig'),
        ('chat', '0005_alter_message_confidence_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationInteraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('shown', 'Shown to User'), ('clicked', 'User Clicked'), ('added_to_cart', 'Added to Cart'), ('ordered', 'Ordered'), ('ignored', 'Ignored')], help_text='Type of interaction', max_length=20)),
                ('recommendation_context', models.JSONField(blank=True, default=dict, help_text='Context at time of recommendation (weather, time, etc.)')),
                ('score', models.FloatField(blank=True, help_text='Recommendation score', null=True)),
                ('position', models.IntegerField(blank=True, help_text='Position in recommendation list', null=True)),
                ('rating', models.IntegerField(blank=True, help_text='User rating if provided', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When interaction occurred')),
                ('menu_item', models.ForeignKey(help_text='Recommended menu item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_interactions', to='dishes.menuitem')),
                ('restaurant', models.ForeignKey(help_text='Restaurant context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_interactions', to='restaurants.restaurant')),
                ('room', models.ForeignKey(help_text='Chat room where recommendation occurred', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_interactions', to='chat.chatroom')),
                ('user', models.ForeignKey(help_text='User who received recommendation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommendation Interaction',
                'verbose_name_plural': 'Recommendation Interactions',
                'db_table': 'recommendation_interactions',
                'indexes': [models.Index(fields=['user', 'created_at'], name='recommendat_user_id_6c88df_idx'), models.Index(fields=['restaurant', 'created_at'], name='recommendat_restaur_e7d9a5_idx'), models.Index(fields=['menu_item', 'interaction_type'], name='recommendat_menu_it_770031_idx'), models.Index(fields=['interaction_type', 'created_at'], name='recommendat_interac_00faa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_count', models.IntegerField(default=0, help_text='Number of messages in session')),
                ('escalated', models.BooleanField(default=False, help_text='Whether session was escalated to human')),
                ('resolved', models.BooleanField(default=False, help_text="Whether user's issue was resolved")),
                ('avg_response_time', models.FloatField(blank=True, help_text='Average response time in seconds', null=True)),
                ('total_response_time', models.FloatField(default=0.0, help_text='Total response time for all messages')),
                ('session_start', models.DateTimeField(auto_now_add=True, help_text='Session start time')),
                ('session_end', models.DateTimeField(blank=True, help_text='Session end time', null=True)),
                ('intents', models.JSONField(blank=True, default=list, help_text='List of intents covered in session')),
                ('satisfaction_score', models.IntegerField(blank=True, help_text='Overall session satisfaction', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('restaurant', models.ForeignKey(help_text='Restaurant context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to='restaurants.restaurant')),
                ('room', models.ForeignKey(help_text='Associated chat room', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chat.chatroom')),
                ('user', models.ForeignKey(help_text='User in session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Session',
                'verbose_name_plural': 'Chatbot Sessions',
                'db_table': 'chatbot_sessions',
                'indexes': [models.Index(fields=['user', 'session_start'], name='chatbot_ses_user_id_5447c5_idx'), models.Index(fields=['restaurant', 'session_start'], name='chatbot_ses_restaur_128545_idx'), models.Index(fields=['escalated', 'session_start'], name='chatbot_ses_escalat_747400_idx'), models.Index(fields=['session_start'], name='chatbot_ses_session_7e0222_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotFeedback',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('recommendation', 'Recommendation Feedback'), ('response', 'Response Quality'), ('escalation', 'Escalation Feedback')], help_text='Type of feedback', max_length=20)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], help_text='User rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('intent', models.CharField(blank=True, help_text='Intent that triggered the response', max_length=50, null=True)),
                ('response_content', models.TextField(blank=True, help_text='Bot response that was rated')),
                ('user_comment', models.TextField(blank=True, help_text='Optional user comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When feedback was given')),
                ('session_id', models.CharField(blank=True, help_text='Session identifier for tracking', max_length=100)),
                ('accepted_items', models.ManyToManyField(blank=True, help_text='Items that user accepted/ordered', related_name='feedback_accepted', to='dishes.menuitem')),
                ('restaurant', models.ForeignKey(help_text='Restaurant context', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_feedbacks', to='restaurants.restaurant')),
                ('room', models.ForeignKey(help_text='Chat room where feedback was given', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='chat.chatroom')),
                ('suggested_items', models.ManyToManyField(blank=True, help_text='Items that were suggested', related_name='feedback_suggestions', to='dishes.menuitem')),
                ('user', models.ForeignKey(help_text='User who provided feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Feedback',
                'verbose_name_plural': 'Chatbot Feedbacks',
                'db_table': 'chatbot_feedback',
                'indexes': [models.Index(fields=['user', 'created_at'], name='chatbot_fee_user_id_0c6953_idx'), models.Index(fields=['restaurant', 'created_at'], name='chatbot_fee_restaur_cc4b32_idx'), models.Index(fields=['feedback_type', 'rating'], name='chatbot_fee_feedbac_d63582_idx'), models.Index(fields=['created_at'], name='chatbot_fee_created_252acc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChatbotAnalytics',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('daily_interactions', 'Daily Interactions'), ('intent_accuracy', 'Intent Classification Accuracy'), ('recommendation_acceptance', 'Recommendation Acceptance Rate'), ('escalation_rate', 'Escalation Rate'), ('avg_response_time', 'Average Response Time'), ('user_satisfaction', 'User Satisfaction Score'), ('error_rate', 'Error Rate')], help_text='Type of metric', max_length=50)),
                ('date', models.DateField(help_text='Date for these metrics')),
                ('value', models.DecimalField(decimal_places=2, help_text='Metric value', max_digits=15)),
                ('count', models.IntegerField(default=0, help_text='Sample count (for averages)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metric details')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When metric was recorded')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When metric was last updated')),
                ('restaurant', models.ForeignKey(help_text='Restaurant for these metrics', on_delete=django.db.models.deletion.CASCADE, related_name='chatbot_analytics', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Chatbot Analytics',
                'verbose_name_plural': 'Chatbot Analytics',
                'db_table': 'chatbot_analytics',
                'indexes': [models.Index(fields=['restaurant', 'date'], name='chatbot_ana_restaur_62f5dd_idx'), models.Index(fields=['metric_type', 'date'], name='chatbot_ana_metric__d49b72_idx'), models.Index(fields=['date'], name='chatbot_ana_date_eef877_idx')],
                'unique_together': {('restaurant', 'metric_type', 'date')},
            },
        ),
    ]
