# Generated by Django 4.2.23 on 2026-01-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_add_chatbot_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotfeedback',
            name='response_content',
            field=models.TextField(blank=True, help_text='Bot response that was rated', null=True),
        ),
    ]
