# Generated by Django 4.2.23 on 2026-01-06 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_fix_feedback_response_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối')),
                ('is_online', models.BooleanField(default=True, help_text='Đang online')),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Lần cuối thấy hoạt động')),
                ('room', models.ForeignKey(blank=True, help_text='Phòng chat đang hoạt động (null nếu chỉ online chung)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_presences', to='chat.chatroom')),
                ('user', models.ForeignKey(help_text='Người dùng', on_delete=django.db.models.deletion.CASCADE, related_name='online_presences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Presence',
                'verbose_name_plural': 'Online Presences',
                'db_table': 'online_presences',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['user', '-last_seen'], name='online_pres_user_id_ee234d_idx'), models.Index(fields=['room', '-last_seen'], name='online_pres_room_id_706512_idx'), models.Index(fields=['is_online', '-last_seen'], name='online_pres_is_onli_707000_idx')],
            },
        ),
    ]
