# Generated by Django 4.2.23 on 2026-01-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_online_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Văn bản'), ('image', 'Hình ảnh'), ('file', 'File'), ('system', 'Hệ thống'), ('chatbot', 'Chatbot')], default='text', help_text='Loại tin nhắn', max_length=20),
        ),
    ]
